server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/byteExpress?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: admin1q2w3e4
      database: 8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.byteexpress.springboot.mybatisplus.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl