server:
  port: 8080

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: admin
    password: secret

  profiles:
    default: main
    # 可使用命令行切换。多个配置将取合集，且后续相同的配置将覆盖前一个
    active: main, ext
    # 不能使用命令行切换
    include:
      - main
      - ext
  # 引入扩展配置
  config:
    import:
      - optional:classpath:/config/ext.yml


---
# Map相关配置
map:
  # 通过配置类配置示例
  byclass:
    property1:
      key1: 'value1'
      key2: 'value2'
  # 通过@Value配置示例。因为yaml语法中如果一个值以{开头，YAML将认为它是一个字典, 所以我们引用它必须用"包起来
  byvalue:
    property1: "{
      key1: 'value1',
      key2: 'value2'
    }"

---
# List相关配置
list:
  # 通过配置类配置示例
  byclass:
    #单行配置
    property1: topic1,topic2,topic3
    #多行配置。@Value的方式也可以注入
    property2: 1,
      2,
      1,
      3
    #多行配置。@Value的方式注入不了，只能用配置类的方式
    property3:
      - topic1
      - topic2
      - topic3
  # 通过@Value配置示例
  byvalue:
    #单行配置
    property1: topic1,topic2,topic3
    #多行配置。
    property2: 1,
      2,
      1,
      3

---
#随机生成值配置
rd:
  #生成随机字母数字字符串
  randomString: ${random.value}
  #生成随机字符串（UUID）
  randomStringUuid: ${random.uuid}
  #整型数字
  randomInt: ${random.int}
  #按指定整型数字范围生成
  randomIntInRange: ${random.int[8080,9999]}
  #长整型
  randomLong: ${random.long}
